# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ScheduleBuilder' do
  
  pod 'SwiftyJSON', '~> 2.3'
  pod 'PagingMenuController', '~> 0.8'
  
end



